export const CATEGORIES = [
  { value: "bioscoop", label: "Bioscoop" },
  { value: "theater", label: "Theater" },
  { value: "sport", label: "Sport" },
  { value: "museum", label: "Museum" },
  { value: "bowling", label: "Bowling" },
  { value: "klimbos", label: "Klimbos" },
  { value: "escaperoom", label: "Escaperoom" },
  { value: "arcade", label: "Arcade" },
  { value: "verhuur", label: "Verhuur" },
  { value: "paintball", label: "Paintball" },
  { value: "concert", label: "Concert" },
  { value: "voetbal", label: "Voetbal" },
  { value: "basketbal", label: "Basketbal" },
  { value: "jeu_de_boules", label: "Jeu de boules" },
  { value: "shuffleboard", label: "Shuffleboard" },
  { value: "boulderen", label: "Boulderen" },
  { value: "pitch_putt", label: "Pitch & Putt" },
  { value: "voet_darts", label: "Voet-darts" },
  { value: "voetgolf", label: "Voetgolf" },
  { value: "minigolf", label: "Minigolf" },
  { value: "padel", label: "Padel" },
  { value: "pickleball", label: "Pickleball" },
  { value: "tennis", label: "Tennis" },
  { value: "karten", label: "Karten" },
  { value: "pool", label: "Pool" },
  { value: "airhockey", label: "Airhockey" },
  { value: "darts", label: "Darts" },
  { value: "rondvaart", label: "Rondvaart" },
  { value: "workshop", label: "Workshop" },
  { value: "cocktail_walk", label: "Cocktail Walk" },
  { value: "bierproeverij", label: "Bierproeverij" },
  { value: "indoor_golf", label: "Indoor Golf" },
  { value: "overig", label: "Overig" },
] as const;

export const CATEGORY_LABELS: Record<string, string> = {
  bioscoop: "Bioscoop",
  theater: "Theater",
  sport: "Sport",
  museum: "Museum",
  bowling: "Bowling",
  klimbos: "Klimbos",
  escaperoom: "Escaperoom",
  arcade: "Arcade",
  verhuur: "Verhuur",
  paintball: "Paintball",
  concert: "Concert",
  voetbal: "Voetbal",
  basketbal: "Basketbal",
  jeu_de_boules: "Jeu de boules",
  shuffleboard: "Shuffleboard",
  boulderen: "Boulderen",
  pitch_putt: "Pitch & Putt",
  voet_darts: "Voet-darts",
  voetgolf: "Voetgolf",
  minigolf: "Minigolf",
  padel: "Padel",
  pickleball: "Pickleball",
  tennis: "Tennis",
  karten: "Karten",
  pool: "Pool",
  airhockey: "Airhockey",
  darts: "Darts",
  rondvaart: "Rondvaart",
  workshop: "Workshop",
  cocktail_walk: "Cocktail Walk",
  bierproeverij: "Bierproeverij",
  overig: "Overig",
};

export type VenueCategory = typeof CATEGORIES[number]["value"];
